### ISSUE TITLE
Bug in afsi.thermal

### ISSUE THREAD

**Issue by pbonofig** [ascot4fusion/ascot5#109]
I believe there is a small bug in afsi.thermal. 

I came across this because I was looking at alphas and neutrons in stellarator geometries where toroidal angle matters. 

The default value in afsi.thermal for maxphi = 2*pi. However, the phi array is assigned the units of degrees (phi = stuff*unyt.deg).

I believe either:
1. maxphi=360 should be the default
or
2. The phi values are converted from radians to degrees before assigning unyt.deg

**Comment by pbonofig** [comment]
Actually, I thought this was a units issue, but something else is going on. 

When I look at the phi-distribution, it is pretty much at phi=0 and nowhere else, and I am not sure why? I would expect a uniform sampling in phi:
![Screen Shot 2024-06-03 at 2 54 27 PM](https://github.com/ascot4fusion/ascot5/assets/92681388/3fd192b6-d6dd-4eff-b409-d8066e0e3fbb)
![Screen Shot 2024-06-03 at 2 54 27 PM](https://github.com/ascot4fusion/ascot5/assets/92681388/3fd192b6-d6dd-4eff-b409-d8066e0e3fbb)

**Comment by pbonofig** [comment]
Even stranger, when I set minphi=pi/4 or to some other value, the distribution is still only near phi=0.

Also, when I use markergen, to generate markers for input, when nphi=1 for afsi.thermal, then the markers are uniform in phi from [0,360], but the (R,Z)-locations are only from phi=0. When nphi>1, then the phi distribution is like that above (nphi=30).

**Comment by miekkasarki** [comment]
Could you please clarify if the issue is in the markergen or already at afsi? Neither of those has been properly used for stellarators (at least I haven't) so it's likely that there are bugs related to 3D geometry.

Those distributions are from the afsi output, correct?

**Comment by miekkasarki** [comment]
I'm able to reproduce this issue with the AFSI tutorial test case. I'll try to fix this within this week.

**Comment by pbonofig** [comment]
Thanks, please let me know when you have a fix. 

I believe the bug similarly applies to afst.beamthermal. I find things are reasonable when one eliminates toroidal dependence (minphi=0, maxphi=2pi, nphi=1) in both the thermal and beam distributions in regards to total source value, but any phi-dependence makes incorrect source profiles.

As I noted in the slack channel, this may propagate to markergen as well, or be an entirely separate bug. Currently, markergen's (R,Z) values do not agree with the phi-angle (at least in 3D geometries).

**Comment by miekkasarki** [comment]
I think I managed to hunt down the bug. I already pushed it to the develop so could you use that (or cherry-pick commit 27bf73f) to see if the issue is gone? Thanks for spotting this error!

Let me know if there is still a separate issue with the markergen.

**Comment by pbonofig** [comment]
Thank you! I have just done some quick tests:

1. My initial tests show much more reasonable toroidal profiles for thermal and beam.thermal afsi sources. I have some lingering questions about the total and thermal sources, though, which I will try to discuss in tomorrow's garage. One such question is: When nphi is increased, so does the total source rate. But what if I want to know the total source rate? How many bins should I choose? I suppose the source rate goes up with nphi because you are simply adding more bins for MC markers?

2. See the below quick and dirty screenshots. They are of alphas from markergen. The one plot is the corresponding phi per particle id (100k particles). It is clearly uniform in [0,360]. The other plot are the corresponding (R,Z) locations. These only match with the phi=0=180 flux surfaces for my stellarator. The plot range extends to 4.2 in R where I would expect more points at different toroidal angles. So, **yes, there also appears to be a bug in markergen regarding the mapping of the (R,Z) locations to the correct toroidal angle.**

![Screen Shot 2024-06-11 at 12 05 46 PM](https://github.com/ascot4fusion/ascot5/assets/92681388/03443179-0e7b-4ec3-ad44-16c88b21f571)
![Screen Shot 2024-06-11 at 12 06 16 PM](https://github.com/ascot4fusion/ascot5/assets/92681388/4dd3404f-47cc-4edb-946f-b603445ce542)

**Comment by miekkasarki** [comment]
Okay, I'll try to have a look at the marker generator as well. The relevant code is rather simple and it's [here ](https://github.com/ascot4fusion/ascot5/blob/main/a5py/routines/markergen.py) in case you want to have a look as well:
