### ISSUE TITLE
Recording GO results as GCs (RECORD_MODE=1) results in 1e4 times more particles in the fast ion distribution

### ISSUE THREAD

**Issue by Ian-Dolby** [ascot4fusion/ascot5#119]
When I record gyro-orbit runs as GCs (`RECORD_MODE = 1`), the FI distribution contains orders of magnitude (1e4) more particles.
I get this result even with the ASCOT5 [distributions tutorial](https://ascot4fusion.github.io/ascot5/tutorials/distributions.html) setup.
I have not changed any distribution values between the two settings, and all of the GO particles are always within the distribution boundaries, so I am not accidentally reducing the number of particles by them going outside.
The total number of particles is obtained by using
`dist.integrate(r=np.s_[:], phi=np.s_[:], z=np.s_[:], ppar=np.s_[:], pperp=np.s_[:],charge=np.s_[:], time=np.s_[:],  copy=True).distribution().v`

The results for the tutorial are below:
FI total: 0.09996 (**GC**), 0.10007 (**GO**), 939.321, (**GO as GC**).
![Figure_5](https://github.com/user-attachments/assets/6b7ec6c2-0c3d-4966-8ddc-ec230ba85fee)
![Figure_1](https://github.com/user-attachments/assets/6caafc2d-cfe3-4de7-b217-870e1cc02894)
![Figure_3](https://github.com/user-attachments/assets/01f1af1a-fb29-4bdd-bfab-757311b5965d)

![Figure_6](https://github.com/user-attachments/assets/1741ed72-c019-4534-ae71-944411c6588f)
![Figure_2](https://github.com/user-attachments/assets/d9367058-c570-415d-b968-02e9f29ca4de)
![Figure_4](https://github.com/user-attachments/assets/3e8d4f4a-4c57-4b36-b8a9-9ffc73346d1e)

I found equivalent issues when recording the COM distribution in previous simulations.

**Comment by Ian-Dolby** [comment]
The phase space volume elements obtained using `dist.phasespacevolume()` are identical, and the difference is coming from the histograms.

**Comment by miekkasarki** [comment]
Interesting... What RECORD_MODE=1 does, is that it makes a guiding center transformation and then updates the distributions as usual (i.e. as they are updated in pure GC simulation). Maybe the weight is not copied? I'll have a look.

Nice catch!

**Comment by miekkasarki** [comment]
This should be now fixed in branch `[feature/119-recording-go-as-gc-brokes-distributions](https://github.com/ascot4fusion/ascot5/tree/feature/119-recording-go-as-gc-brokes-distributions)`.

Can you confirm @Ian-Dolby ?

**Comment by Ian-Dolby** [comment]
The discrepancy is now only ~5e3 instead of 1e4, but it is still there. I have done `git switch` and `git fetch`, and done `make clean` and then  `make ascot5_main -j MPI=0 VERBOSE=1 FLAGS="-g" CC=gcc` and `make libascot -j MPI=0 VERBOSE=1 FLAGS="-g" CC=gcc`, so I'm fairly confident that I am testing the new version. 

The new plots are quite similar to the old ones.

**Comment by Ian-Dolby** [comment]
The simulations from that tutorial are set up with a time limit of 10 ms, but the difference remains even with a longer time limit.

**Comment by Ian-Dolby** [comment]
Update:  I made a mistake in rerunning the simulations and I was accidentally still using a previous version.

The agreement is now extremely good, within 0.1% for even quick simulations with 1e-4 s sim times.

**Comment by miekkasarki** [comment]
Great! This fix will be in the next release.
