### ISSUE TITLE
wrong dimension in copy data to gpu

### ISSUE THREAD

**Issue by peyberne** [ascot4fusion/ascot5#130]
In 'src/copytogpu.c' the dimension used for 'sim->plasma_data.plasma_1D.temp' array is wrong.

**Comment by miekkasarki** [comment]
Yup, your fix is correct! The temperature data only has ion and electron temperature (and not separate T for every species). I could merge this immediately to the develop branch, if this is ok for you?

**Comment by peyberne** [comment]
yes, ok for me !

**Comment by miekkasarki** [comment]
Now fixed in develop branch
