### ISSUE TITLE
ASCOT5 won't build on Mac OS Sonoma 14.0 - immintrin.h library not found

### ISSUE THREAD

**Issue by lcarbajal-t1e** [ascot4fusion/ascot5#17]
Hi ASCOT Team,

I am testing ASCOT5 on a MacBook Pro with Apple Silicon running Sonoma 14.0, for this I had to use GNU compilers V12, instead of V10 as suggested in the documentation. GNU compilers V10 won't install well using MacPorts. 
The issue popping up while compiling is that gcc won't find immintrin.h library in my system, this library is used in ascot5/simulate/simulate_*.c code files. If I comment the line for including this library in all ascot5/simulate/simulate_*.c files, the error goes away and I am able to build ascot5_main and libascot, even run a test simulation.
The question is: is immintrin.h used in some way so I shouldn't be dropping that dependency? or is OK to don't use it?
Thanks.
Leo

**Comment by miekkasarki** [comment]
Hi Leo,

If that would break something, it would be the vectorization. But you are probably not going to run large simulations on your MacBook, so it shouldn't matter.

If you can run the introduction simulation and the results seem fine, I'd say you're good to go!

@jvarje Do you recall what exactly is included from "immintrin.h" and should it be put behind preprocessor directives if it is optional?
