### ISSUE TITLE
Possible bug in a5.markergen.generate method

### ISSUE THREAD

**Issue by Antonjvv** [ascot4fusion/ascot5#78]
When generating markers for ascot (from a bbnbi results distribution) using a5.markergen.generate as follows:
nmrk   = 4000
anum   = 1
znum   = 1
mass   = 1.007*unyt.amu
charge = 1.0*unyt.e
dist = a5_run_tcv.data.active.getdist("5d")
dist.integrate(charge=np.s_[:], time=np.s_[:])
mrk = a5_run_tcv.markergen.generate(nmrk, mass, charge, anum, znum
plt.scatter(mrk["pitch"], mrk["energy"])
![image_480](https://github.com/ascot4fusion/ascot5/assets/71718077/cf3513f6-2ef0-421f-bda2-22b5bfb0148d)

The markers pitch and energy distribution appears to be changed from the bbnbi5 result markers:
mrk = a5_run_tcv.data.active.getstate_markers("gc")
plt.scatter(mrk["pitch"], mrk["energy"])
![image_480](https://github.com/ascot4fusion/ascot5/assets/71718077/cdd2bf98-e70b-4b3c-bdca-ca32fc2b13e5)

**Comment by miekkasarki** [comment]
In tutorials there is this plot which is obtained in the same way as the buggy plot you posted, but the one in the tutorials seem fine. https://ascot4fusion.github.io/ascot5/_images/tutorials_markergen_13_0.png

This makes me think that the bug is actually in the BBNBI distribution output. Did you plot the distribution you get from `a5_run_tcv.data.active.getdist("5d")` in momentum space and did it look ok?

**Comment by miekkasarki** [comment]
Just to clarify: even if BBNBI distribution is broken, the result (i.e. marker output) seems fine, so it is likely that only the diagnostics is broken and nothing is wrong in the physics.

**Comment by miekkasarki** [comment]
I managed to reproduce this. The BBNBI distribution is ok, so the bug is somewhere within the markergen.

**Comment by miekkasarki** [comment]
Ok, it does not appear to be a bug, but an artefact produced by having a too coarse (ppar, pperp) grid. @Antonjvv what where your distribution settings in the options? I used 100 x 200 grid for (ppar,pperp) and that produced tolerable results. Eventually we will have implement (ekin,pitch) grid fro BBNBI and Ascot.

**Comment by miekkasarki** [comment]
Yeah, that's unfortunately from the grid. We will have to implement (energy,pitch) distributions directly in Ascot's C-kernel (so that BBNBI and AFSI output can be in these coordinates) to make better use of the marker generator tool.

**Comment by lcarbajal-t1e** [comment]
@miekkasarki I'm having an issue with the function a5.markergen.rhoto5d(), after running an AFSI simulation for a 3-D stellarator case (via a5.afsi.thermal() function), I can generate well the markers (alpha-particles) only when running this on a Mac (Sonoma 14.5) but every time I try to run it on a linux machine it crashes with the error "Segmentation fault (core dumped)", I've tried three different linux systems all with the same result. Any chance this is related to this issue? is there any way to diagnose what could be going wrong?
I'm using ASCOT 5.5.4, and installing with conda (h5cc wrapper using gcc (conda-forge gcc 12.3.0-7) 12.3.0 ). Please, advice if I should file a new issue. 
Thanks!

**Comment by miekkasarki** [comment]
> @miekkasarki I'm having an issue with the function a5.markergen.rhoto5d(), after running an AFSI simulation for a 3-D stellarator case (via a5.afsi.thermal() function), I can generate well the markers (alpha-particles) only when running this on a Mac (Sonoma 14.5) but every time I try to run it on a linux machine it crashes with the error "Segmentation fault (core dumped)", I've tried three different linux systems all with the same result. Any chance this is related to this issue? is there any way to diagnose what could be going wrong? I'm using ASCOT 5.5.4, and installing with conda (h5cc wrapper using gcc (conda-forge gcc 12.3.0-7) 12.3.0 ). Please, advice if I should file a new issue. Thanks!

@lcarbajal-t1e I'll make a new issue from this as it could be stellarator-specific.

**Comment by miekkasarki** [comment]
I believe this issue is solved. Please comment or raise a new issue if new problems arise.

(The AFSI grid now supports energy-pitch basis.)
