### ISSUE TITLE
Markergen support for rho5d distributions.

### ISSUE THREAD

**Issue by Otsooni** [ascot4fusion/ascot5#89]
The current implementation of markergen does not support sampling from rho5d distributions. Important people (me) need this feature, so I will work on it.

I planned to implement it in the same function (markergen.generate) that would automatically make the distinction between distributions from the abscissae labels. However, I didn't know if anyone (like @miekkasarki) had any plans for the function.

**Comment by miekkasarki** [comment]
It's "proof-of-principle" function/module. Feel free to expand it anyway you like.

Sure it can autodetect the distribution, but the actual implementation could be separated to private functions.

For this particular feature, I think the existing tools take you far. Once you have sampled (rho,phi,theta) coordinates, then use the mapping `input__rhotheta2rz` to convert those to cylindrical coordinates.
